rust-embedded/blog

- content/2018-08-2x-psa-cortex-m-breakage.md
> remove redundant quote and update the text

- content/2018-08-28-newsletter-10.md
Sorry to spam PRs. Just fixing things as I see them.
> Fix a link, add reddit callout

- ci/install.sh
- ci/script.sh
this should run linkchecker on the output of gutenberg
r? @rust-embedded/resources (anyone)
> run linkchecker

- content/2018-09-09-newsletter-11.md
Closes #6 
I can update the social media links after the initial merge.
> 11th newsletter, initial commit

- content/2018-09-25-newsletter-12.md
> Newsletter 12

- content/2018-10-09-newsletter-13.md
Better like this?
r? @thejpster
> Use canonical reddit link

- content/2019-03-06-newsletter-16.md
Full disclosure - I work at 42 Technology and I wrote the nRF9160 demo.
> Add nRF9160 announcement

- content/2019-03-20-newsletter-17.md
- content/2019-04-05-newsletter-18.md
> Add content for newsletter 17, polish it up, and add a template for 18

- content/2019-06-02-newsletter-18.md
- content/2019-07-02-newsletter-18.md
As requested on IRC :)
There are a few TODOs I haven't handled yet, since I'm not entirely sure what the correct procedure is. Date has been bumped to today (UTC+2).
> Newsletter 18: Matrix section and various release preparation

- content/2019-07-02-newsletter-18.md
Aaargh :( I really should not be writing this sort of stuff late at night... Apologies for the flood of last-minute corrections!
> Newsletter 18: fix typo in channel name

- content/2019-09-26-newsletter-19.md
> Add VEML6075 driver

- content/2019-10-03-newsletter-19.md
I was sick with the flu last week, and wasn't able to post the blog. Let's push back one more week.
> Reschedule post, add crate counts

- content/2019-10-31-newsletter-20.md
> Add docker image

- content/2019-10-31-newsletter-20.md
Adding my XMC rust embedded crates
> Adding information about XMC crates

- content/2019-11-05-newsletter-20.md
- content/2019-11-28-newsletter-21.md
and add no_std WIP to crate counts
> Reschedule and finalize newsletter 20, set up 21

- content/2019-11-28-newsletter-21.md
I've put together a set of crates to support Rust development on the Teensy 4. It's very early stages, and I'd love to get feedback from the broader embedded Rust community on the approach.
> Add teensy4-rs blurb in 2019-11-28 newsletter

- content/2019-11-28-newsletter-21.md
- content/2019-12-26-newsletter-22.md
Also replaces #80, which was stuck with a merge conflict
> November release

- content/2019-11-28-newsletter-21.md
> Welcome to the social

- content/2019-12-26-newsletter-22.md
I thought this would be of interest for the community.
> Add Si4703 FM radio receiver driver entry

- content/2019-12-26-newsletter-22.md
> Add PCA9685 PWM LED/Servo controller driver

- content/2019-12-26-newsletter-22.md
I just noticed the driver is also compatible with VEML7700.
> Note compatibility with VEML7700 ALS

- content/2020-01-01-newsletter-22.md
- content/2020-01-30-newsletter-23.md
~~Don't merge until @Yatekii adds probe-rs stuff~~
> Prep for Newsletter 22 release

- content/2020-01-30-newsletter-23.md
Adds note about max7219 driver release (release done before last newsletter but I forgot to mention it)
> add max7219 crate release

- content/2020-01-30-newsletter-23.md
Note about release, and link to blog post.
> Add a note about Infrared

- content/2020-02-29-newsletter-24.md
> Newsletter 24: Add shtcx crate to projects section

- content/2020-02-29-newsletter-24.md
It feels wrong to add this under "Highlights", but according to the comments, that's where everything that's not a crate release should go.
> Add article about DW1000 to newsletter

- content/2020-08-17-newsletter-24.md
- content/2020-08-24-newsletter-25.md
Working on #121!
CC @eldruin @hargoniX @kalkyl, @therealprof, there are a couple to-dos left before we can publish:
1. ~We need to fill in all the placeholder links (like this: `[text](#)`) with actual links~
2. ~We need to count up the diffs for the Ecosystem crates at the bottom~ Done!
I think the best way to do this is to submit suggested changes, and we can merge them as they are ready. We can squash the final merge to keep the commit count down.
I'll have some more time later today to work on this, but feel free to contrib if you have time!
> Newsletter revival

- content/2020-08-24-newsletter-25.md
A project of mine, hope it's good enough to be included :)
> Add embedded-text

- content/2020-08-24-newsletter-25.md
Add bits about the ESP8266 wifi offloading.
> Wifi Offloading.

- content/2020-08-31-newsletter-26.md
Don't hesitate to correct it! (I'm not native)
> 2020-08-31 Blog post: Rust, Arduino and Embedded Development as a Beginner: Part 1

- content/2020-09-28-newsletter-26.md
Hey @rust-embedded/resources, I think we've caught up, so I'd propose we postpone the next article to 1month after the last one. Let me know if this works for you!
> Postpone as we've caught up

- content/2020-09-28-newsletter-26.md
Hi! This PR adds some knurling-rs news to the newsletter. I've used indented bullet points to structure the info but if that takes up too much space I'll be happy to edit them down.
> newsletter 26: add knurling news

- content/2021-02-16-newsletter-26.md
- content/2021-03-16-newsletter-27.md
Signed-off-by: Daniel Egger <daniel@eggers-club.de>
> Ready newsletter 26 for publication

- content/2021-03-16-newsletter-27.md
I integrated it into the existing item for RampMaker 0.2 and shifted some content to the Flott newsletter item further above.
> Add Stepper 0.5 announcement

- content/2021-05-07-newsletter-29.md
as per https://github.com/rust-embedded/showcase/pull/28#pullrequestreview-710594188 :)
> Add midikraken to 2021-05-07-newsletter-29.md

- content/2021-05-07-newsletter-29.md
I think we can probably get this issue published at last, after this.
> Add cortex-m-rt release announcement and cross call for help

- content/2021-11-16-newsletter-30.md
- content/newsletter-next.md
Signed-off-by: Daniel Egger <daniel@eggers-club.de>
> Finalize 30th newletter and add template for 31

- content/2021-12-28-newsletter-31.md
- content/newsletter-next.md
As edited at https://hackmd.io/@znpl-20YQ0icKHOXR9EpQw/SywUu_iqK
> Add 2021 round-up.

- content/2021-12-28-this-year-in-embedded-rust-2021.md
- content/newsletter-next.md
Updated title to match the previous "this year in embedded rust" post and set draft to false to get it published.
> Change title and publish TYIER

- content/newsletter-next.md
As suggested in today's WG meeting.
> Announce Rust support in RIOT

- content/2022-03-22-newsletter-31.md
- content/newsletter-next.md
> Publish newsletter 31
